services:
  ###################################################
  # Service: proxy
  #
  ###################################################
  proxy:
    image: traefik:v3.6
    command: --providers.docker
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  ###################################################
  # Service: backend
  ###################################################
  backend:
    build:
      context: ./
      target: backend-dev
    command: npm run start:dev
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DATABASE: nsc_events
      JWT_SECRET: secret
    depends_on:
      postgres:
        condition: service_healthy
    labels:
      traefik.http.routers.backend.rule: Host(`localhost`) && PathPrefix(`/api`)
      traefik.http.services.backend.loadbalancer.server.port: 3000

  ###################################################
  # Service: client
  ###################################################
  client:
    build:
      context: ./
      target: client-dev
    ports:
      - "3000:8080"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost/api
    labels:
      traefik.http.routers.client.rule: Host(`localhost`)
      traefik.http.services.client.loadbalancer.server.port: 8080

  ###################################################
  # Service: postgres
  ###################################################
  postgres:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: nsc_events
    ports:
      - "3307:5432"
    volumes:
      - nsc-events-postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  ###################################################
  # Service: pgadmin
  ###################################################
  pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    ports:
      - "5050:80"
    labels:
      traefik.http.routers.pgadmin.rule: Host(`db.localhost`)
      traefik.http.services.pgadmin.loadbalancer.server.port: 80

volumes:
  nsc-events-postgres-data: