name: Monorepo CI (on pull-request)
run-name: PR from branch ${{ github.head_ref }}

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            frontend:
              - 'nsc-events-nextjs/**'
              - '!nsc-events-nextjs/**/*.md'
              - '!nsc-events-nextjs/LICENSE*'
              - '!nsc-events-nextjs/.gitignore'
              - '!nsc-events-nextjs/.prettierrc'
              - '!nsc-events-nextjs/.eslintrc.js'
            backend:
              - 'nsc-events-nestjs/**'
              - '!nsc-events-nestjs/**/*.md'
              - '!nsc-events-nestjs/LICENSE*'
              - '!nsc-events-nestjs/.gitignore'
              - '!nsc-events-nestjs/.prettierrc'
              - '!nsc-events-nestjs/.eslintrc.js'

  frontend-ci:
    needs: detect-changes
    if: needs.detect-changes.outputs.frontend == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"
          cache: "npm"
          cache-dependency-path: 'package-lock.json'
      - name: Clean install dependencies
        run: HUSKY=0 npm ci
      - name: Run linter
        run: npm run lint
        working-directory: ./nsc-events-nextjs
      - name: Compile typescript
        run: npm run compile
        working-directory: ./nsc-events-nextjs
      - name: Jest unit tests
        run: npm run test
        working-directory: ./nsc-events-nextjs
      - name: Build App
        run: npm run build
        working-directory: ./nsc-events-nextjs

  backend-ci:
    needs: detect-changes
    if: needs.detect-changes.outputs.backend == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 22
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'
      - name: Clean install dependencies
        run: HUSKY=0 npm ci --include=optional
      - name: Install sharp for Linux platform
        run: npm install --os=linux --cpu=x64 sharp
        working-directory: ./nsc-events-nestjs
      - name: Run linter
        run: npm run lint
        working-directory: ./nsc-events-nestjs
      - name: Compile typescript
        run: npm run compile
        working-directory: ./nsc-events-nestjs
      - name: Test coverage
        run: npm run test:cov
        working-directory: ./nsc-events-nestjs
      - name: Build App
        run: npm run build --if-present
        working-directory: ./nsc-events-nestjs
